import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const html = readFileSync(join(root, 'index.html'), 'utf8');
const css = readFileSync(join(root, 'style.css'), 'utf8');
const js = readFileSync(join(root, 'game.js'), 'utf8');

assert.match(html, /aria-label="Choose your bird character"/, 'character picker should be exposed to assistive tech');
assert.match(html, /data-character="classic"/, 'classic bird option should exist');
assert.match(html, /data-character="ruby"/, 'ruby bird option should exist');
assert.match(html, /data-character="midnight"/, 'midnight bird option should exist');
assert.match(html, /data-character="eagle"/, 'eagle bird option should exist');
assert.match(html, /data-character="sugar"/, 'Sugar Star bird option should exist');
assert.match(html, /data-character="sixseven"/, 'secret 6/7 bird option should exist in locked state');
assert.match(html, /data-character="clock"/, 'Logan secret clock option should exist in locked state');
assert.match(html, /data-character="duck"/, '30-point duck option should exist in locked state');
assert.match(html, /<span>Eagle<\/span>/, 'Eagle option should be labeled Eagle');
assert.match(html, /<span>Sugar Star<\/span>/, 'Sugar Star option should use the full Sugar Star name');
assert.match(html, /<span>Duck<\/span>/, 'duck option should be labeled Duck');
assert.match(html, /<span>Clock<\/span>/, 'clock option should be labeled Clock');
assert.match(
  html,
  /data-character="classic"[\s\S]*data-character="ruby"[\s\S]*data-character="midnight"[\s\S]*data-character="eagle"[\s\S]*data-character="duck"[\s\S]*data-character="sixseven"[\s\S]*data-character="clock"[\s\S]*data-character="sugar"/,
  'character menu should be sorted as immediately playable, then Eagle, score unlocks, then secret code unlocks'
);
assert.match(html, /id="selectedCharacterText"/, 'selected character label should exist');
assert.match(html, /id="secretButton"[^>]*>Secret<\/button>/, 'secret unlock button should sit on the start overlay');
assert.match(html, /id="secretCodeInput"/, 'secret code input should exist for unlock flow');
assert.match(html, /id="secretSubmitButton"/, 'secret code submit button should exist');

assert.match(css, /\.character-picker/, 'character picker styles should exist');
assert.match(css, /\.character-option\.selected/, 'selected character styling should exist');
assert.match(css, /\.secret-unlock/, 'secret unlock form styling should exist');
assert.match(css, /\.character-option\.locked/, 'locked secret character styling should exist');

assert.match(js, /const CHARACTERS = \[/, 'character definitions should exist');
assert.match(js, /id: 'sixseven'/, 'secret 6/7 character should be defined');
assert.match(js, /name: 'Six Seven'/, 'secret character should be named for 6 and 7');
assert.match(js, /id: 'duck'/, 'duck character should be defined');
assert.match(js, /name: 'Emerald Duck'/, 'duck character should be named');
assert.match(js, /id: 'eagle'/, 'eagle character should be defined');
assert.match(js, /name: 'Sky Eagle'/, 'eagle character should be named');
assert.match(js, /species: 'eagle'/, 'eagle character should use eagle sprite-sheet rendering');
assert.match(js, /assets\/eagle-sprite-sheet\.png/, 'eagle sprite sheet asset should be referenced');
assert.match(js, /id: 'sugar'/, 'Sugar Star character should be defined');
assert.match(js, /name: 'Sugar Star'/, 'Sugar Star character should be named');
assert.match(js, /id: 'sugar'[\s\S]*locked: true[\s\S]*secretCode: 'queenlia'/, 'Sugar Star should be locked behind the Queen Lia secret code');
assert.match(js, /id: 'sugar'[\s\S]*species: 'sugar'[\s\S]*body: '#ffffff'[\s\S]*crest: '#f8fafc'[\s\S]*wing: '#e2e8f0'[\s\S]*beak: '#ffffff'[\s\S]*beakShadow: '#94a3b8'[\s\S]*eye: '#ffffff'[\s\S]*pupil: '#0f172a'[\s\S]*shadow: '#64748b'/, 'Sugar Star should be unmistakably white/silver with visible contrast');
assert.match(js, /id: 'sugar'[\s\S]*sparklyEyes: true/, 'Sugar Star should have sparkly eyes');
assert.match(js, /character\.species === 'sugar'/, 'Sugar Star should use a dedicated sprite branch instead of falling through to classic bird drawing');
assert.match(js, /drawSugarStarSprite\(targetCtx, character, wingY\)/, 'Sugar Star should use a dedicated high-contrast white sprite renderer');
assert.doesNotMatch(js, /id: 'sugar'[\s\S]*?(#facc15|#fde047|#eab308|#fb923c|#f97316)[\s\S]*?sparklyEyes: true/, 'Sugar Star must not reuse Classic Yellow palette colors');
assert.match(js, /id: 'clock'[\s\S]*id: 'sugar'/, 'Sugar Star should be grouped after existing secret-code characters');
assert.match(js, /id: 'clock'/, 'clock character should be defined');
assert.match(js, /name: 'Logan Clock'/, 'clock character should be named for its secret code');
assert.match(js, /secretCode: 'logan'/, 'clock should unlock with the Logan secret code');
assert.match(js, /species: 'clock'/, 'clock character should use clock-specific drawing and background behavior');
assert.match(js, /unlockScore: 30/, 'duck should unlock when the player reaches 30 points');
assert.match(js, /species: 'duck'/, 'duck character should use duck-specific drawing and audio behavior');
assert.match(js, /body: '#16a34a'/, 'duck should use a green body');
assert.match(js, /crest: '#f8fafc'/, 'duck should use white feathers');
assert.match(js, /STORAGE_KEY_CHARACTER/, 'selected non-secret character should be persisted');
assert.doesNotMatch(js, /STORAGE_KEY_SECRET_CHARACTER/, 'secret unlock should reset each time the game page starts');
assert.doesNotMatch(js, /localStorage\.setItem\([^)]*SECRET/i, 'secret unlock should not be saved to localStorage');
assert.match(js, /let secretCharacterUnlocked = false;/, 'secret character should start locked for each page session');
assert.match(js, /let clockCharacterUnlocked = false;/, 'clock secret character should start locked for each page session');
assert.match(js, /let sugarCharacterUnlocked = false;/, 'Sugar Star should start locked for each page session');
assert.match(js, /SECRET_UNLOCK_CODE = 'ilove67'/, 'secret unlock code should be ilove67');
assert.match(js, /function selectCharacter/, 'character selection handler should exist');
assert.match(js, /Enter the secret code to unlock this character\./, 'locked secret character click should show the requested unlock message');
assert.match(js, /function unlockSecretCharacter/, 'secret character unlock handler should exist');
assert.match(js, /document\.addEventListener\('pointerdown', \(event\) => \{[\s\S]*if \(event\.target === secretCodeInput\) return;[\s\S]*if \(event\.target\.closest\('button'\)\) return;[\s\S]*flap\(\);[\s\S]*\}\);/, 'pointer taps on the secret code input should not start the game');
assert.match(js, /enteredCode === 'logan'[\s\S]*clockCharacterUnlocked = true;[\s\S]*selectCharacter\('clock'\)/, 'Logan code should unlock and select the clock character');
assert.match(js, /enteredCode === SECRET_UNLOCK_CODE[\s\S]*secretCharacterUnlocked = true;[\s\S]*selectCharacter\('sixseven'\)/, 'ilove67 code should still unlock and select Six Seven');
assert.match(js, /enteredCode\.replace\(\/\\s\+\/g, ''\) === 'queenlia'[\s\S]*sugarCharacterUnlocked = true;[\s\S]*selectCharacter\('sugar'\)/, 'Queen Lia or QueenLia should unlock and select Sugar Star');
assert.match(js, /function syncSecretCharacterLockState/, 'secret character should stay locked until code entry');
assert.match(js, /character\.unlockScore <= Math\.max\(score, bestScore\)/, 'score-locked characters should unlock at their score threshold');
assert.match(js, /score \+= 1;[\s\S]*syncSecretCharacterLockState\(\)/, 'character locks should refresh when scoring points');
assert.match(js, /function drawCharacterPreview/, 'character picker preview renderer should exist');
assert.match(js, /function drawBirdSprite/, 'game bird should be drawn from selected character data');
assert.match(js, /function drawEagleSprite\(/, 'eagle character should have a dedicated sprite renderer');
assert.match(js, /const EAGLE_FLAP_FRAME_MS = 220;/, 'eagle flap should advance more slowly than the earlier 95ms cadence');
assert.match(js, /const EAGLE_FLAP_CYCLE_MS = EAGLE_FLAP_FRAME_MS \* EAGLE_SPRITE_FRAMES\.length;/, 'eagle flap should use a full-cycle duration');
assert.match(js, /const EAGLE_FLAP_BOB_AMPLITUDE = 1\.6;/, 'eagle bob should stay subtle');
assert.match(js, /localProgress = framePosition - Math\.floor\(framePosition\);[\s\S]*easedBlend = localProgress \* localProgress \* \(3 - 2 \* localProgress\)/, 'eagle sprite should ease between frames for smoother motion');
assert.match(js, /globalAlpha = 1 - easedBlend;[\s\S]*globalAlpha = easedBlend;/, 'eagle sprite should crossfade adjacent frames');
assert.match(js, /function drawBird\(now = performance\.now\(\)\)/, 'bird renderer should accept a shared animation timestamp');
assert.match(js, /function draw\(now = performance\.now\(\)\)/, 'main draw loop should pass the frame timestamp through');
assert.match(js, /character\.badge === '67'/, 'bird sprite should draw a 67 badge for the secret character');
assert.match(js, /character\.species === 'clock'/, 'clock sprite should draw clock-specific details');
assert.match(js, /character\.species === 'eagle'/, 'eagle sprite should use the sprite sheet branch');
assert.match(js, /targetCtx\.arc\(0, -3, 18, 0, Math\.PI \* 2\)/, 'clock character should have a round clock face');
assert.match(js, /targetCtx\.moveTo\(0, -3\);[\s\S]*targetCtx\.lineTo\(0, -14\);[\s\S]*targetCtx\.moveTo\(0, -3\);[\s\S]*targetCtx\.lineTo\(9, -3\)/, 'clock character should draw clock hands');
assert.match(js, /if \(character\.sparklyEyes\) \{[\s\S]*targetCtx\.fillRect\(4, -14, 2, 2\);[\s\S]*targetCtx\.fillRect\(9, -9, 2, 2\);[\s\S]*\}/, 'sparkly-eyed characters should draw eye sparkle pixels');
assert.match(js, /function drawClockCloud\(x, y, scale\)/, 'clock clouds should have a dedicated renderer');
assert.match(js, /getSelectedCharacter\(\)\.species === 'clock' \? drawClockCloud\(x, y, 2 \+ \(i % 2\)\) : pixelCloud\(x, y, 2 \+ \(i % 2\)\)/, 'clock character should turn background clouds into round clocks');
assert.match(js, /ctx\.arc\(x \+ radius, y \+ radius, radius, 0, Math\.PI \* 2\)/, 'clock clouds should be round clock faces');
assert.match(js, /ctx\.lineTo\(x \+ radius, y \+ radius \* 0\.45\)/, 'clock clouds should draw minute hands');
assert.match(js, /character\.species === 'duck'/, 'duck sprite should draw duck-specific details');
assert.match(js, /fillRect\(12, -7, 26, 12\)/, 'duck should have a longer bill');
assert.match(js, /font = '900 16px monospace'/, 'secret 67 badge digits should be even larger');

console.log('character-selection checks passed');
